### ISSUE TITLE
Please, correct readme

### ISSUE THREAD

**Issue by kopach** [AVVS/node-transliteration#2]
This is not cyrylic -> lain transliteration at all. It's **Russian -> English transliteration**, which is important!
There are lots of languages which use cyrylic and each of them have specific pronunciation of some cyrylic letters, plus usually have some language specific cyrylic characters.
Moreover, there are even more languages that uses latin alphabet. Try to transliterate Russian -> Polish here https://www.ushuaia.pl/transliterate/ and you'll see, that it's very different from Russian -> English.

**Comment by AVVS** [comment]
https://github.com/AVVS/node-transliteration/commit/ab15eec215ea5a196a2d0d2267b5090ab5b0595b

hope this works ;) thanks for the note

You are also very welcome to add desired languages and update API, though you might look into `icu` family of projects, which give comprehensive transliteration for many other languages

**Comment by kopach** [comment]
np. and thanks for `icu` family projects suggestion. Didn't know about that, will take a look.
